#!/bin/sh

ESC="\033["
BLACK="${ESC}30m"
RED="${ESC}31m"
GREEN="${ESC}32m"
YELLOW="${ESC}33m"
BLUE="${ESC}34m"
MAGENTA="${ESC}35m"
CYAN="${ESC}36m"
WHITE="${ESC}97m"

function cd_back_on_flag()
{
    if [[ "" != "$FLAG_CD_BACK" ]]; then
        cd - &>/dev/null
    fi
}

##### INPUT PARSING #####

# foreach word in inputs
#     if word and word+1 are of the form "-k|--key value"
#         set variables accordingly
#     else
#         add the value to positional array for later
#     shift inputs foreach processed word (if 2 words, then $1 = $3 and $2 = $4)
ENV="release"
POSITIONAL=()

while [[ $# -gt 0 ]]; do
  key="$1"

    case $key in
        -e|--ENV)
            ENV="$2"
            shift; shift
            ;;
        *)
            POSITIONAL+=("$1")
            shift
            ;;
    esac
done

##### MOVE INTO THE DIRECTORY #####

# cd if positional arg or pipe provided
FLAG_CD_BACK=""
if [ "" != "$POSITIONAL" ]; then
    cd "$POSITIONAL" 2>/dev/null || {
        echo "${RED}Dir. [${YELLOW}$POSITIONAL${RED}] does not exist.${WHITE}"
        exit 1
    }
    FLAG_CD_BACK=1
else
    if [ -p /dev/stdin ]; then
        read -e line
        if [ "" != "$line" ]; then
            if [[ $line =~ ^~\/.*$ ]]; then
                line="${HOME}/${line#"~/"}"
            fi
            cd $line  || {
                echo "${RED}Dir. [${YELLOW}$line${RED}] does not exist.${WHITE}"
                exit 1
            }
            FLAG_CD_BACK=1
        fi
    fi
fi

# pier import specific case
if [[ "pier-import" ==  "${PWD##*/}" && "$ENV" == "release" ]]; then
    ENV="demo"
fi

# verify directory is a git repo
if [ "" == "$(git rev-parse --is-inside-work-tree 2>/dev/null)" ]; then
    echo "${RED}Not a Git repository.${WHITE}"
    exit 1
fi

##### GIT STUFF #####
TAG=$(git tag | grep $ENV | sort -V | tail -n 1)
TAG="${TAG##*-}"
TAG=$(($TAG + 1))

##### DEPLOY BY PUSHING TAG #####
case $ENV in
    release) COLOR="$YELLOW" ;;
    demo)    COLOR="$BLUE"   ;;
    prod)    COLOR="$RED"    ;;
esac

echo "Tagging for env [${COLOR}$ENV${WHITE}]: -- ${GREEN}$TAG${WHITE} --"

read -p "Continue ? [y/N] " -n 1 -r confirm </dev/tty
echo
if [[ ! $confirm =~ ^[Yy]$ ]]; then
    echo "Aborted."
    cd_back_on_flag
    exit 1
fi

git tag $ENV-$TAG
git push origin $ENV-$TAG

cd_back_on_flag
echo "Done."